server:
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://ping-me-db-instance.cqqdco6tediw.us-east-2.rds.amazonaws.com:5432/ping_me
    username: postgres
    password: pingmepostgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: 'classpath:/db/changelog-master.yaml'

amazon-properties:
  bucket-name:
    profile-picture: ping-me-profile-pictures

#cloud:
#  aws:
#    credentials:
#      access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
    com:
      project:
        pingme:
          service:
            impl: DEBUG
          controller: DEBUG
    feign: TRACE
